add common operations
mishaprokop4ik/brainfuck pull request #5
Opened 2022-03-22 16:53 UTC by mishaprokop4ik

2022-03-23 15:26 UTC, VitaliyShevchenko commented
pls add a good description of the PR, attach some results of unit tests and manual testing.

2022-03-23 15:27 UTC, VitaliyShevchenko commented
<img width="465" alt="Screenshot 2022-03-23 at 17 26 47" src="https://user-images.githubusercontent.com/11538767/159735262-b3b65f1f-f67a-4871-93de-55b290e15e19.png">

only one commit. In the future pls try to separate it to more commits which will be smaller

2022-03-23 15:29 UTC, VitaliyShevchenko commented
not sure why `.DS_Store` is needed. Pls remove it. If you need it pls reply to this comment with a reason.

2022-03-23 15:42 UTC, VitaliyShevchenko requested changes

2022-03-23 15:42 UTC, VitaliyShevchenko commented on internal/interpreter/brainfuck.go
> +func Interpret(program string)  {
docs

2022-03-23 15:42 UTC, VitaliyShevchenko commented on internal/interpreter/operations.go
> +package interpreter
pls add docs for all public structs/funcs

2022-03-23 15:42 UTC, VitaliyShevchenko commented on internal/interpreter/memory.go
> +package interpreter
pls add docs for all public structs/funcs

2022-03-23 15:42 UTC, VitaliyShevchenko commented on internal/interpreter/brainfuck.go
> +package interpreter
pls add a doc for a package.

2022-03-23 15:42 UTC, VitaliyShevchenko commented on internal/interpreter/brainfuck.go
> +		if o, ok := commands[symbol]; ok {
what is `o`? Pls give proper name to a variable

2022-03-23 15:42 UTC, VitaliyShevchenko commented on internal/interpreter/brainfuck.go
> +			panic(fmt.Sprintf("unexpected symbol in brainfuck %s in %d place", string(symbol), i+1))
why panic? you can just return an error in this case.

2022-03-23 15:42 UTC, VitaliyShevchenko commented on internal/interpreter/memory.go
> +func newMemory(m int) *memory {
m ? Please give proper name to this argument

2022-03-23 15:42 UTC, VitaliyShevchenko commented on internal/interpreter/brainfuck.go
> +	fmt.Println()
why is this needed? Pls remove it

2022-03-23 15:42 UTC, VitaliyShevchenko commented on internal/interpreter/operations.go
> +type operation interface {
private interface with public func? What is the purpose?

2022-03-23 15:42 UTC, VitaliyShevchenko commented on cmd/main.go
> +package main
pls read docs about `cmd` folder: https://github.com/golang-standards/project-layout/blob/master/cmd/README.md

I don't think it's suitable in this case

2022-03-23 15:42 UTC, VitaliyShevchenko commented on internal/interpreter/brainfuck.go
> +package interpreter
pls add tests for this file

2022-03-23 15:42 UTC, VitaliyShevchenko commented on internal/interpreter/memory.go
> +var commands = map[rune]instruction{
just curios why did you declare commands in memory.go file?

2022-03-23 15:42 UTC, VitaliyShevchenko commented on internal/interpreter/operations.go
> +package interpreter
pls add tests for this file

2022-03-23 16:15 UTC, mishaprokop4ik commented on internal/interpreter/brainfuck.go
> +			panic(fmt.Sprintf("unexpected symbol in brainfuck %s in %d place", string(symbol), i+1))
but why?
I think it's like unexpected operation in input program and like in Go, if we write, for example, fun instead of func go compile will argue and program will stop

2022-03-23 16:18 UTC, mishaprokop4ik commented on internal/interpreter/brainfuck.go
> +	fmt.Println()
so I have to remove it?

2022-03-23 16:34 UTC, mishaprokop4ik commented on internal/interpreter/memory.go
> +var commands = map[rune]instruction{
I wanted to highlight that commands in memory in brainfuck interpreter and commands like independent of realisation of operations in operations.go file

2022-03-23 16:38 UTC, mishaprokop4ik commented on internal/interpreter/brainfuck.go
> +package interpreter
i added tests in different one pr [there](https://github.com/mishaprokop4ik/brainfuck/pull/7)

2022-03-23 18:59 UTC, mishaprokop4ik commented on internal/interpreter/operations.go
> +package interpreter
fixed

2022-03-23 18:59 UTC, mishaprokop4ik commented on internal/interpreter/memory.go
> +var commands = map[rune]instruction{
fixed

2022-03-23 18:59 UTC, mishaprokop4ik commented on internal/interpreter/brainfuck.go
> +package interpreter
merge pr to this branch. fixed

2022-03-23 18:59 UTC, mishaprokop4ik commented on cmd/main.go
> +package main
fixed

2022-03-23 18:59 UTC, mishaprokop4ik commented on internal/interpreter/operations.go
> +type operation interface {
fixed

2022-03-23 19:00 UTC, mishaprokop4ik commented on internal/interpreter/brainfuck.go
> +		if o, ok := commands[symbol]; ok {
fixed

2022-03-23 19:00 UTC, mishaprokop4ik commented on internal/interpreter/brainfuck.go
> +package interpreter
added. fixed

2022-03-23 19:00 UTC, mishaprokop4ik commented on internal/interpreter/memory.go
> +package interpreter
added. fixed

2022-03-23 19:00 UTC, mishaprokop4ik commented on internal/interpreter/operations.go
> +package interpreter
added. fixed

2022-03-23 19:00 UTC, mishaprokop4ik commented on internal/interpreter/brainfuck.go
> +func Interpret(program string)  {
added. fixed

2022-03-23 19:05 UTC, mishaprokop4ik commented
> pls add a good description of the PR, attach some results of unit tests and manual testing.

I think I deal with it:)

2022-03-24 17:17 UTC, VitaliyShevchenko commented on internal/interpreter/brainfuck.go
> +	fmt.Println()
yes pls

2022-03-24 17:20 UTC, VitaliyShevchenko commented
> > not sure why `.DS_Store` is needed. Pls remove it. If you need it pls reply to this comment with a reason.
> 
> removed. could you tell me why did this file appear. I didn't see him.

that's interesting actually.. 
Pls read this: https://github.com/2DegreesInvesting/resources/issues/115

I just found it.

2022-03-24 17:21 UTC, VitaliyShevchenko commented
do you think having nested `internal` folder is good in this case?

2022-03-24 17:33 UTC, VitaliyShevchenko requested changes

2022-03-24 17:33 UTC, VitaliyShevchenko commented on internal/interpreter/brainfuck.go
> +func Interpret(program string) {
pls add a doc

2022-03-24 17:33 UTC, VitaliyShevchenko commented on internal/interpreter/brainfuck_test.go
> +		{
what about a scenario where the program has some incorrect symbol? Pls add a test for that scenario too.

2022-03-24 17:33 UTC, VitaliyShevchenko commented on internal/interpreter/operations.go
> +// incrementPointer it is a struct that implement operation interface
`it` is redundant.. just `incrementPointer is a struct.. bla bla`

2022-03-24 17:33 UTC, VitaliyShevchenko commented on internal/interpreter/operations.go
> +// it increment pointer by one
`it incrementS`

2022-03-24 17:33 UTC, VitaliyShevchenko commented on internal/interpreter/operations_test.go
> +		preOperations []operation
why do you need this strange `preOperations` logic? The idea here:
1. Have a loop command with a list of inner commands
2. Execute loop command
3. Check where the pointer and memory

That's it.

2022-03-24 17:33 UTC, VitaliyShevchenko commented on internal/interpreter/brainfuck_test.go
> +			Interpret(tt.args)
I don't see that you assert the output.. 
You will have to:
1. Run `Interpret`
2. Get the result of this command
3. Compare it to what you are expecting to see

2022-03-24 17:33 UTC, VitaliyShevchenko commented on internal/interpreter/operations_test.go
> +func TestIncrementCell_Execute(t *testing.T) {
pls add a test for `output` command

2022-03-24 17:33 UTC, VitaliyShevchenko commented on README.md
>  Use the git to install interpreter.
this will just clone the repo. To install it, you will need to execute: `go get ...`

2022-03-24 17:33 UTC, VitaliyShevchenko commented on README.md
>  Simple brainfuck interpreter for options to extensions
pls add info about ALL Make commands that the others case use.

2022-03-24 17:33 UTC, VitaliyShevchenko commented on README.md
> +Unit tests coverage: 91.4% of statements. Manual tests:
I don't think this test converage is needed for end user. I think how to run the tests is much better info that you can share.

2022-03-24 17:33 UTC, VitaliyShevchenko commented on .gitignore
>  /.idea/
what about go binary? we don't need to push to repo.

2022-03-24 17:33 UTC, VitaliyShevchenko commented on Makefile
> +test:
you can add a command which will be a binary

2022-03-24 19:04 UTC, mishaprokop4ik commented on internal/interpreter/brainfuck.go
> +func Interpret(program string) {
I will do it. But it will be copy of doc of interpreter package in doc.go

2022-03-24 20:21 UTC, mishaprokop4ik commented
> do you think having nested `internal` folder is good in this case?

yes, you could see anouther one pr, I added `input` nested folder in in `internal`

2022-03-24 20:23 UTC, mishaprokop4ik commented
> > > not sure why `.DS_Store` is needed. Pls remove it. If you need it pls reply to this comment with a reason.
> > 
> > 
> > removed. could you tell me why did this file appear. I didn't see him.
> 
> that's interesting actually.. Pls read this: [2DegreesInvesting/resources#115](https://github.com/2DegreesInvesting/resources/issues/115)
> 
> I just found it.

thanks!

2022-03-24 20:26 UTC, mishaprokop4ik commented on main.go
> +// nolint
if you are about adding `nolint` comment I added it because of string length. And could I ask you to check anouther pr where I added operations to read brainfuck program from files

2022-03-24 20:32 UTC, mishaprokop4ik commented on internal/interpreter/brainfuck.go
> +func Interpret(program string) {
fixed

2022-03-24 20:32 UTC, mishaprokop4ik commented on internal/interpreter/operations.go
> +// incrementPointer it is a struct that implement operation interface
fixed

2022-03-24 20:47 UTC, mishaprokop4ik commented on internal/interpreter/brainfuck_test.go
> +		{
added. fixed

2022-03-24 20:47 UTC, mishaprokop4ik commented on README.md
>  Simple brainfuck interpreter for options to extensions
added

2022-03-24 20:48 UTC, mishaprokop4ik commented on .gitignore
>  /.idea/
added

2022-03-24 20:48 UTC, mishaprokop4ik commented on Makefile
> +test:
added

2022-03-24 20:53 UTC, mishaprokop4ik commented on README.md
> +Unit tests coverage: 91.4% of statements. Manual tests:
fixed. added

2022-03-24 21:05 UTC, mishaprokop4ik commented on internal/interpreter/operations_test.go
> +		preOperations []operation
I added `preOperations` to check loop commands work correctly. Like loop will be working while pointer is not zero.
I will add test without `preOperations`

2022-03-24 21:06 UTC, mishaprokop4ik commented on internal/interpreter/brainfuck_test.go
> +			Interpret(tt.args)
fixed)

2022-03-24 21:47 UTC, mishaprokop4ik commented on internal/interpreter/brainfuck.go
> +	fmt.Println()
fixed

2022-03-24 21:47 UTC, mishaprokop4ik commented on internal/interpreter/memory.go
> +func newMemory(m int) *memory {
fixed

2022-03-24 21:48 UTC, mishaprokop4ik commented on internal/interpreter/operations_test.go
> +func TestIncrementCell_Execute(t *testing.T) {
added

2022-03-24 21:50 UTC, mishaprokop4ik commented on README.md
>  Use the git to install interpreter.
sorry for stupid question. but i just need to replace `git clone...` to `go get...`?
as I know I have to add my package to go get codebase

2022-03-24 22:06 UTC, mishaprokop4ik commented
@VitaliyShevchenko can I merge `input_file` branch in this or after review this and `input_file` branch?

2022-03-30 10:55 UTC, VitaliyShevchenko requested changes

2022-03-30 10:55 UTC, VitaliyShevchenko commented on Makefile
> +BIN_NAME := payroll
just wondering why binary name is `payroll` ?

2022-03-30 10:55 UTC, VitaliyShevchenko commented on README.md
>  Use the git to install interpreter.
with `git clone`, you will just clone the project locally right? But as a user I want to just `go get github.com/mishaprokop4ik/brainfuck`, which will install  brainfuck on my local machine and then call `brainfuck.Interpret`. Or the second option is to just import it somewhere in my project and use it.

2022-03-30 10:55 UTC, VitaliyShevchenko commented on README.md
> +#### To run tests run from cmd write:
pls write about lint too. also probably some other make commands which will be useful

2022-03-30 10:55 UTC, VitaliyShevchenko commented on internal/interpreter/brainfuck.go
> +// Interpret run brainfuck programs
Interpret runS

2022-03-30 10:55 UTC, VitaliyShevchenko commented on internal/interpreter/brainfuck.go
> +// Interpret run brainfuck programs
pls add more details on what exactly this func does. A programmer who reads this doc should understand a behaviour of this func without looking at the implementation.

2022-03-30 10:55 UTC, VitaliyShevchenko commented on internal/interpreter/brainfuck.go
> +func findCommands(program string) []operation {
findCommands func returns operation list. There two ways of fixing it:
1. renaming `operation` to command
2. rename `findCommands` to `findOperations`
after that it will be much understandable

2022-03-30 10:55 UTC, VitaliyShevchenko commented on internal/interpreter/brainfuck.go
> +			panic(fmt.Sprintf("unexpected symbol in brainfuck %s in %d place", string(symbol), i+1))
agreed. pls write about that in the docs. A user should know about that limitation. Also pls add a test for that scenario.

2022-03-30 10:55 UTC, VitaliyShevchenko commented on internal/interpreter/brainfuck.go
> +		if inst, ok := instructions[symbol]; ok {
`instruction` or `i`, but not something in the middle :)

2022-03-30 10:55 UTC, VitaliyShevchenko commented on internal/interpreter/operations.go
> +	fmt.Fprint(m.out, string(m.cells[m.pointer]))
why not just `fmt.Println` ? this was you will not need `io.Writer` in memory struct.

2022-03-30 10:55 UTC, VitaliyShevchenko commented on internal/interpreter/operations.go
> +type incrementPointer struct{}
incrementPointer implements operation interface
this is redundant in the doc.
what if in the future we will have a different interface name? or different interface at all? in this we will have to change the doc, which we don't want to do.

2022-03-30 10:55 UTC, VitaliyShevchenko commented on internal/interpreter/brainfuck_test.go
> +	Interpret("-[------->+<]>-.-[->+++++<]>++.+++++++..+++.[--->+<]>-----.--[->++++<]>-.--------.+++.------.--------.-[--->+<]>.")
a test should have some expected output and real output. Then you will have to run `Interpret` and compare the expected output with real one.

Now this test checks nothing. Pls fix that.

2022-03-30 10:55 UTC, VitaliyShevchenko commented on internal/interpreter/brainfuck_test.go
> +				if p := recover(); p != nil && tt.name == "unexpected symbol" {
the test should fail if something goes wrong

2022-03-30 10:55 UTC, VitaliyShevchenko commented on internal/interpreter/doc.go
> +// Package interpreter interpreter package provides options to run brainfuck programs.
interpreter interpreter interpreter interpreter interpreter interpreter interpreter interpreter
Let's have more `interpreter` :) 

Pls rewrite this doc.

2022-03-30 10:55 UTC, VitaliyShevchenko commented on internal/interpreter/memory.go
> +func addOperation(stack *[][]operation, o operation) {
are you sure that this is a good place to have addOperation func here?
(inside memnory.go)

2022-03-30 10:55 UTC, VitaliyShevchenko commented on internal/interpreter/memory.go
> +var instructions = map[rune]instruction{
are you sure that this is a good place to have instructions map here?
(inside memnory.go)

2022-03-30 11:40 UTC, mishaprokop4ik commented on internal/interpreter/operations.go
> +	fmt.Fprint(m.out, string(m.cells[m.pointer]))
because of test. To check output I need to have this `fmt.Fprint`. 
In test I have buffer, you can check it in `operation_test.go -> TestOutput_Execute`

2022-03-30 11:42 UTC, mishaprokop4ik commented on Makefile
> +BIN_NAME := payroll
I got skeleton of makefile from my old project, I've just seen it too)

2022-03-30 11:45 UTC, mishaprokop4ik commented on internal/interpreter/doc.go
> +// Package interpreter interpreter package provides options to run brainfuck programs.
ou, it is golint said to do it)

2022-03-30 11:47 UTC, mishaprokop4ik commented on internal/interpreter/doc.go
> +// Package interpreter interpreter package provides options to run brainfuck programs.
<img width="1058" alt="Screenshot 2022-03-30 at 14 47 31" src="https://user-images.githubusercontent.com/73275046/160827579-a370e656-e497-4064-938f-51207fb20e52.png">

2022-03-30 11:54 UTC, mishaprokop4ik commented on internal/interpreter/brainfuck_test.go
> +	Interpret("-[------->+<]>-.-[->+++++<]>++.+++++++..+++.[--->+<]>-----.--[->++++<]>-.--------.+++.------.--------.-[--->+<]>.")
<img width="116" alt="Screenshot 2022-03-30 at 14 54 08" src="https://user-images.githubusercontent.com/73275046/160828689-4217ae2c-a544-4690-a315-f7ba0e0d03e4.png">
this kinda checks. I will fix it

2022-03-30 17:38 UTC, mishaprokop4ik commented on internal/interpreter/brainfuck_test.go
> +	Interpret("-[------->+<]>-.-[->+++++<]>++.+++++++..+++.[--->+<]>-----.--[->++++<]>-.--------.+++.------.--------.-[--->+<]>.")
fixed

2022-03-30 17:38 UTC, mishaprokop4ik commented on internal/interpreter/brainfuck_test.go
> +				if p := recover(); p != nil && tt.name == "unexpected symbol" {
fixed

2022-03-30 17:39 UTC, mishaprokop4ik commented on internal/interpreter/brainfuck.go
> +// Interpret run brainfuck programs
fixed

2022-03-30 17:46 UTC, mishaprokop4ik commented on internal/interpreter/brainfuck.go
> +func findCommands(program string) []operation {
fixed

2022-03-30 17:46 UTC, mishaprokop4ik commented on internal/interpreter/brainfuck.go
> +		if inst, ok := instructions[symbol]; ok {
fixed

2022-03-30 17:46 UTC, mishaprokop4ik commented on internal/interpreter/operations.go
> +type incrementPointer struct{}
fixed

2022-03-30 17:47 UTC, mishaprokop4ik commented on internal/interpreter/doc.go
> +// Package interpreter interpreter package provides options to run brainfuck programs.
fixed

2022-03-30 17:47 UTC, mishaprokop4ik commented on README.md
> +#### To run tests run from cmd write:
fixed

2022-03-30 17:49 UTC, mishaprokop4ik commented on internal/interpreter/memory.go
> +var instructions = map[rune]instruction{
yap:). I older wrote it why I choose this option

2022-03-30 17:49 UTC, mishaprokop4ik commented on internal/interpreter/memory.go
> +func addOperation(stack *[][]operation, o operation) {
yap:). I older wrote it why I choose this option

2022-03-30 17:50 UTC, mishaprokop4ik commented on README.md
>  Use the git to install interpreter.
fixed

2022-04-04 18:23 UTC, VitaliyShevchenko commented on internal/interpreter/operations.go
> +	fmt.Fprint(m.out, string(m.cells[m.pointer]))
we should not change an implementation because of the tests..

2022-04-04 19:41 UTC, mishaprokop4ik commented on internal/interpreter/operations.go
> +	fmt.Fprint(m.out, string(m.cells[m.pointer]))
yep). but `fmt.Fpintf` gets `io.Writer` interface, so we dont change implementation. in tests to check correct value I just change `io.Writer` datatype to bytes.buffer to get option to read wrote data and make tests not useless.
and also, I can give option to end-user to write output of program to console or other output channels.
or did I not correct understand you?

2022-04-11 11:20 UTC, VitaliyShevchenko requested changes

2022-04-11 11:20 UTC, VitaliyShevchenko commented on Makefile
> +BIN_NAME := payroll
is it fixed?  pls remove it at all

2022-04-11 11:20 UTC, VitaliyShevchenko commented on README.md
>  Use the git to install interpreter.
`Use the git to install interpreter`. are you sure it's GIT ?

2022-04-11 11:20 UTC, VitaliyShevchenko commented on README.md
> +make test
you already declared a doc for this command

2022-04-11 11:20 UTC, VitaliyShevchenko commented on main.go
> +	interpreter.Interpret("-[------->+<]>-.-[->+++++<]>++.+++++++..+++.", nil)
nil ? pls remove this...

2022-04-11 11:20 UTC, VitaliyShevchenko commented on main.go
> +//const defaultDataIn string = ">++++++++[<+++++++++>-]" +
pls remove all redundant comments from the code

2022-04-11 11:20 UTC, VitaliyShevchenko commented on internal/interpreter/brainfuck.go
> +// Interpret get an brainfuck operations as a string.
`Interpret getS`

2022-04-11 11:20 UTC, VitaliyShevchenko commented on internal/interpreter/brainfuck.go
> +		m = newMemory(memorySize, os.Stdout)
let it be always as `os.Stdout`
no need to add an ability to a user for that

OR

you can provide an ability to choose io.Writer, but you should have some default value or something.

PS. if it's me I will remove this ability at all

2022-04-11 11:20 UTC, VitaliyShevchenko commented on internal/interpreter/memory.go
> +var instructions = map[rune]instruction{
as for me it's better to move it under `brainfuck.go`

2022-04-11 11:20 UTC, VitaliyShevchenko commented on internal/interpreter/memory.go
> +func addOperation(stack *[][]operation, o operation) {
pls link me to your answer

2022-04-11 12:18 UTC, mishaprokop4ik commented on internal/interpreter/brainfuck.go
> +		m = newMemory(memorySize, os.Stdout)
if I remove it, can you tell me to I can test an output data?

2022-04-11 12:27 UTC, mishaprokop4ik commented on main.go
> +//const defaultDataIn string = ">++++++++[<+++++++++>-]" +
fixed

2022-04-11 12:27 UTC, mishaprokop4ik commented on internal/interpreter/brainfuck.go
> +// Interpret get an brainfuck operations as a string.
fixed

2022-04-11 12:27 UTC, mishaprokop4ik commented on README.md
> +make test
fixed

2022-04-11 12:27 UTC, mishaprokop4ik commented on README.md
>  Use the git to install interpreter.
fixed

2022-04-11 12:45 UTC, mishaprokop4ik commented on Makefile
> +BIN_NAME := payroll
unexpected for me I didn't rename it. sorry for lying((

2022-04-20 10:21 UTC, VitaliyShevchenko approved these changes

2022-04-21 20:28 UTC, merged